PRIMARY_DARK_GREEN = "#145319"
SECONDARY_LIGHT_GREEN = "#388E3C"
ACCENT_WARNING_ORANGE = "#D97706"
APP_BACKGROUND = "#F1F5F0"
SURFACE_BACKGROUND = "#FFFFFF"
PRIMARY_TEXT = "#1A2E1A"
ERROR_RED = "#DC2626"
NEUTRAL_GRAY = "#6B7280"
SUCCESS_GREEN = "#16A34A"
RISK_COLORS: dict[str, str] = {
    "LOW": SUCCESS_GREEN,
    "MEDIUM": ACCENT_WARNING_ORANGE,
    "HIGH": "#EA580C",
    "CRITICAL": ERROR_RED,
}
