PRIMARY_DARK_GREEN = "#214916"
SECONDARY_LIGHT_GREEN = "#A9EB35"
ACCENT_WARNING_ORANGE = "#F7DC27"
APP_BACKGROUND = "#297F39"
SURFACE_BACKGROUND = "#FAF8EF"
PRIMARY_TEXT = "#214916"
ERROR_RED = "#F7DC27"
NEUTRAL_GRAY = "#297F39"
SUCCESS_GREEN = "#A9EB35"
RISK_COLORS: dict[str, str] = {
    "LOW": SUCCESS_GREEN,
    "MEDIUM": ACCENT_WARNING_ORANGE,
    "HIGH": ACCENT_WARNING_ORANGE,
    "CRITICAL": ERROR_RED,
}
