PRIMARY_DARK_GREEN = "#1F6E2A"
PRIMARY_GREEN = "#2F8B3A"
SECONDARY_LIGHT_GREEN = "#A8E629"
ACCENT_WARNING_ORANGE = "#F2DB1D"  # Accent Yellow as Warning/Accent
APP_BACKGROUND = "#F2EFE8"
SURFACE_BACKGROUND = "#FFFFFF"
PRIMARY_TEXT = "#1A2E1A"
ERROR_RED = "#D9381E"
NEUTRAL_GRAY = "#849285"
SUCCESS_GREEN = "#A8E629"

RISK_COLORS: dict[str, str] = {
    "LOW": SUCCESS_GREEN,
    "MEDIUM": ACCENT_WARNING_ORANGE,
    "HIGH": "#F29D1D",  # Deeper Orange for HIGH
    "CRITICAL": ERROR_RED,
}
