from pathlib import Path
from zoneinfo import ZoneInfo

APP_TIMEZONE = ZoneInfo("Asia/Jakarta")
TIMEZONE_NAME = "Asia/Jakarta"
DEFAULT_COOPERATIVE_NAME = "Koperasi Tani Merapi Sejahtera"
PILOT_COMMODITY_CODE = "CABAI_RAWIT_MERAH"
PILOT_REGION = "Kabupaten Magelang, Jawa Tengah"
DEFAULT_ADM4_CODE = "33.08.01.2001"
OPERATIONAL_HORIZON_DAYS = 7
PLANNING_HORIZON_DAYS = 14
MAX_HARVEST_FUTURE_DAYS = 90
MAX_HARVEST_QUANTITY_KG = 100000.0
MAX_BUYER_DISTANCE_KM = 1000.0
MAX_CAPACITY_KG = 1000000.0
KG_TOLERANCE = 0.001
BMKG_BASE_URL = "https://api.bmkg.go.id/publik/prakiraan-cuaca"
BMKG_TIMEOUT_SECONDS = 3
BMKG_CACHE_STALE_HOURS = 24
DB_PATH = Path("data/mimpitani.db")
SQLITE_BUSY_TIMEOUT_MS = 5000
SCHEMA_VERSION = 1
RISK_WEIGHT_SUPPLY_DEMAND_GAP = 45
RISK_WEIGHT_HARVEST_CONCENTRATION = 20
RISK_WEIGHT_TRANSPORT_CAPACITY_GAP = 15
RISK_WEIGHT_WEATHER_DISRUPTION = 10
RISK_WEIGHT_ESTIMATE_UNCERTAINTY = 10
RISK_THRESHOLD_MEDIUM = 25.0
RISK_THRESHOLD_HIGH = 50.0
RISK_THRESHOLD_CRITICAL = 75.0
UNALLOCATED_SUPPLY_PENALTY = 1000.0
UNMET_DEMAND_PENALTY = 100.0
LATE_DELIVERY_PENALTY = 10.0
DISTANCE_PENALTY = 1.0
