from enum import StrEnum


class WorkspaceMode(StrEnum):
    DEMO = "DEMO"
    EMPTY = "EMPTY"


class QualityGrade(StrEnum):
    A = "A"
    B = "B"
    C = "C"


class EstimateConfidence(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class BatchStatus(StrEnum):
    PLANNED = "PLANNED"
    CANCELLED = "CANCELLED"


class SourceType(StrEnum):
    MANUAL = "MANUAL"
    CSV = "CSV"
    SEED = "SEED"


class SeedableSource(StrEnum):
    MANUAL = "MANUAL"
    SEED = "SEED"


class ChannelType(StrEnum):
    TRADITIONAL_MARKET = "TRADITIONAL_MARKET"
    RETAILER = "RETAILER"
    RESTAURANT = "RESTAURANT"
    PROCESSOR = "PROCESSOR"


class DemandStatus(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class WeatherSourceStatus(StrEnum):
    LIVE = "LIVE"
    CACHE = "CACHE"
    UNAVAILABLE = "UNAVAILABLE"


class AnalysisRunType(StrEnum):
    BASE = "BASE"
    SCENARIO = "SCENARIO"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SolverStatus(StrEnum):
    OPTIMAL = "OPTIMAL"
    FEASIBLE_FALLBACK = "FEASIBLE_FALLBACK"
    NO_DATA = "NO_DATA"
    FAILED = "FAILED"


class RiskFactorCode(StrEnum):
    SUPPLY_DEMAND_GAP = "SUPPLY_DEMAND_GAP"
    HARVEST_CONCENTRATION = "HARVEST_CONCENTRATION"
    TRANSPORT_CAPACITY_GAP = "TRANSPORT_CAPACITY_GAP"
    WEATHER_DISRUPTION = "WEATHER_DISRUPTION"
    ESTIMATE_UNCERTAINTY = "ESTIMATE_UNCERTAINTY"


class RecommendedActionCode(StrEnum):
    ADD_COMPATIBLE_DEMAND = "ADD_COMPATIBLE_DEMAND"
    INCREASE_CRITICAL_DATE_CAPACITY = "INCREASE_CRITICAL_DATE_CAPACITY"
    VERIFY_LOW_CONFIDENCE_HARVESTS = "VERIFY_LOW_CONFIDENCE_HARVESTS"
    REVIEW_CLUSTERED_HARVEST_DATES = "REVIEW_CLUSTERED_HARVEST_DATES"


class AllocationReasonCode(StrEnum):
    GRADE_COMPATIBLE = "GRADE_COMPATIBLE"
    DEADLINE_FEASIBLE = "DEADLINE_FEASIBLE"
    CAPACITY_AVAILABLE = "CAPACITY_AVAILABLE"
    HIGH_PRIORITY = "HIGH_PRIORITY"
    EARLY_DELIVERY = "EARLY_DELIVERY"
    SHORT_DISTANCE = "SHORT_DISTANCE"
